const c=document.getElementById('map'),ctx=c.getContext('2d');
let center={lon:1.8131,lat:48.7075}, zoom=13.5, gps=null, dragging=false,last=null, data={water:[],hydro:[],commune:[]};
const R=6378137;
function merc(lon,lat){let x=R*lon*Math.PI/180,y=R*Math.log(Math.tan(Math.PI/4+lat*Math.PI/360));return{x,y}}
function inv(x,y){return{lon:x/R*180/Math.PI,lat:(2*Math.atan(Math.exp(y/R))-Math.PI/2)*180/Math.PI}}
function scale(){return 256*Math.pow(2,zoom)/(2*Math.PI*R)}
function screen(lon,lat){let p=merc(lon,lat),m=merc(center.lon,center.lat),s=scale();return{x:c.width/2+(p.x-m.x)*s,y:c.height/2-(p.y-m.y)*s}}
function resize(){let d=devicePixelRatio||1;c.width=innerWidth*d;c.height=innerHeight*d;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0);draw()}
function grid(){ctx.fillStyle='#e6eee5';ctx.fillRect(0,0,innerWidth,innerHeight);ctx.strokeStyle='#cbd9cc';ctx.lineWidth=1;for(let x=0;x<innerWidth;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,innerHeight);ctx.stroke()}for(let y=0;y<innerHeight;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(innerWidth,y);ctx.stroke()}ctx.fillStyle='#667a6b';ctx.font='12px system-ui';ctx.fillText('Fond vectoriel local minimal – données métier hors ligne',12,innerHeight-34)}
function point(lon,lat,r,fill,stroke='#fff'){let p=screen(lon,lat);ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();ctx.lineWidth=2;ctx.strokeStyle=stroke;ctx.stroke();return p}
function line(coords,color='#2681a6',w=2){ctx.beginPath();coords.forEach((q,i)=>{let p=screen(q[0],q[1]);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});ctx.strokeStyle=color;ctx.lineWidth=w;ctx.stroke()}
function drawFeature(f,color){let g=f.geometry;if(!g)return;if(g.type==='Point')point(g.coordinates[0],g.coordinates[1],6,color);if(g.type==='LineString')line(g.coordinates,color,2);if(g.type==='MultiLineString')g.coordinates.forEach(x=>line(x,color,2));}
function draw(){grid(); if(document.getElementById('showHydro').checked)data.hydro.forEach(f=>drawFeature(f,'#2585ad'));if(document.getElementById('showWater').checked)data.water.forEach(f=>drawFeature(f,'#1976a8'));if(document.getElementById('showCommune').checked)data.commune.forEach(f=>drawFeature(f,'#496d54'));if(gps)point(gps.lon,gps.lat,7,'#d22')}
async function load(){for(const [k,f] of [['water','data/plans_eau.geojson'],['hydro','data/hydrographie.geojson'],['commune','data/commune.geojson']]){try{let j=await fetch(f);data[k]=(await j.json()).features||[]}catch(e){}}draw()}
function coordFromEvent(e){let rect=c.getBoundingClientRect();return{x:e.clientX-rect.left,y:e.clientY-rect.top}}
c.addEventListener('pointerdown',e=>{dragging=true;last=coordFromEvent(e);c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!dragging)return;let p=coordFromEvent(e),dx=p.x-last.x,dy=p.y-last.y,m=merc(center.lon,center.lat),s=scale();center=inv(m.x-dx/s,m.y+dy/s);last=p;draw()});c.addEventListener('pointerup',e=>{dragging=false});c.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(10,Math.min(18,zoom+(e.deltaY<0?.5:-.5)));draw()},{passive:false});
c.addEventListener('click',e=>{if(Math.abs(e.movementX||0)+Math.abs(e.movementY||0)>3)return;let p=coordFromEvent(e),best=null,bd=18;data.water.forEach(f=>{if(f.geometry?.type!=='Point')return;let q=screen(...f.geometry.coordinates),d=Math.hypot(q.x-p.x,q.y-p.y);if(d<bd){best=f;bd=d}});if(best){let a=best.properties||{};popup.innerHTML=`<button onclick="popup.classList.add('hidden')">×</button><b>${a.nom||'Point d’eau'}</b>${a.type||''}<br><small>Source : ${a.source||'non renseignée'}<br>Potabilité : ${a.potabilite||'non renseignée'}<br>${a.statut||''}</small>`;popup.classList.remove('hidden')}});
layersBtn.onclick=()=>panel.classList.toggle('hidden');['showWater','showHydro','showCommune'].forEach(id=>document.getElementById(id).onchange=draw);
online.onchange=()=>{status.textContent=online.checked?'Fond OSM en ligne prévu pour V2 • fond local affiché':'Mode hors ligne prêt • données locales';online.checked=false};
gpsBtn.onclick=()=>{if(!navigator.geolocation){status.textContent='GPS non disponible';return}status.textContent='Recherche GPS…';navigator.geolocation.watchPosition(p=>{gps={lon:p.coords.longitude,lat:p.coords.latitude,acc:p.coords.accuracy};center={...gps};zoom=16;gpsBtn.classList.add('active');status.textContent=`GPS ±${Math.round(gps.acc)} m`;draw()},e=>status.textContent='GPS : '+e.message,{enableHighAccuracy:true,maximumAge:5000,timeout:15000})};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});addEventListener('resize',resize);resize();load();
